version: "3.8"

services:
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL:
        # EMAIL_USER:
        # EMAIL_PASS:
        # CLOUDINARY_NAME:
        # CLOUDINARY_API_KEY:
        # CLOUDINARY_SECRET:
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
