version: "3.4"

services:
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
